### ISSUE TITLE
Incomplete repair information

### ISSUE THREAD

**Issue by XanderGryphon** [mcMMO-Dev/mcMMO#1065]
I'm attempting to set mcMMO up to work with some custom items, but keep getting error messages in the console when it attempts to load the armor.yml

"[WARNING] [mcMMO] Incomplete repair information. This item will be unrepairable."

I've configured the armor.yml file as thoroughly as it's asked me to, so I'm at a loss as to what's causing the error.

Below is a small snippet of my file, which has several entries within it, but they all follow the same format:

```
Copper_Helmet:
    ID: 26513
    Repairable: true
    Repair_Material_ID: 26507
    Repair_Material_Data_Value: 0
    Repair_Material_quantity: 5
    Durability: 110
Bronze_Helmet:
    ID: 26663
    Repairable: true
    Repair_Material_ID: 26657
    Repair_Material_Data_Value: 0
    Repair_Material_quantity: 5
    Durability: 143
```

I feel like I've simply overlooked something, but I can't figure out what. Apologies if this is lacking necessary information, I will provide whatever necessary that I can upon request.

mcMMO v1.4.05-b1870
CraftBukkit version git-MCPC-Plus-jenkins-MCPC-plus-397 (MC: 1.5.1)
