### ISSUE TITLE
Advance.yml help D: McMMO

### ISSUE THREAD

**Issue by brendaaan** [mcMMO-Dev/mcMMO#1133]
So I am a complete novice when it comes to editting YAML files and whatnot, but I have read many posts you have contributed to help others and I was wondering if you could guide me in the right direction @_@

I understand that in McMMO, you can edit the advance.yml to change the properties of certain skills, but I edited them and although the axes says "damageincrease_Maxbonus: 4" and i changed the number to 3 and it is achieved at level 500, but it still turns out in-game to be +4 DMG and etc

Also with unarmed, I set the disarm chance to 0 (i'm not sure if that meant no limit or it hopefully set to 0) but its not :'(

(I edit using notepad ++ unless that's not what i should be using D: )

aaaaaaaaaaaaaand in config.yml I set unarmed PVP to false, yet I can hit someone and it does 4.5 hearts of damage at level 500 unarmed when it really shouldn't ):

I would really appreciate your help D: Please and thank you~

-Brendan

```
    #
    #  Settings for Axes
    ###
    Axes:
        # DamageIncrease_MaxBonus: Maximum bonus damage
        # DamageIncrease_MaxBonusLevel: Level where the maximum bonus is reached
        DamageIncrease_MaxBonus: 3
        DamageIncrease_MaxBonusLevel: 500

        # AxesCritical_MaxChance: Maximum chance of causing a critical hit
        # AxesCritical_MaxBonusLevel: Level where the maximum chance of causing critical hits is reached
        AxesCritical_MaxChance: 37.50
        AxesCritical_MaxBonusLevel: 750

        # Damage modifier of critical hits for PVP / PVE, when causing a critical hit the damage gets multiplied by the modifier
        AxesCritical_PVP_Modifier: 1.5
        AxesCritical_PVE_Modifier: 2.0

        # GreaterImpact_Chance: Chance of hitting with GreaterImpact, knocksbacks mobs
        # GreaterImpact_KnockbackModifier: Velocity modifier of GreaterImpact hits, this determines how great the knockback is
        # GreaterImpact_BonusDamage: Extra damage for GreaterImpact hits
        GreaterImpact_Chance: 25.0
        GreaterImpact_KnockbackModifier: 1.5
        GreaterImpact_BonusDamage: 2

        # ArmorImpact_IncreaseLevel: Every "IncreaseLevel" the durability damage goes up with 1
        # ArmorImpact_Chance: Chance of hitting with ArmorImpact
        # ArmorImpact_MaxPercentageDurabilityDamage: Durability damage cap for ArmorImpact, 20% means that you can never destroy a piece of armor in less than 5 hits
        ArmorImpact_IncreaseLevel: 250
        ArmorImpact_Chance: 25.0
        ArmorImpact_MaxPercentageDurabilityDamage: 10.0

        # SkullSplitter_DamageModifier: Damage will get divided by this modifier
        SkullSplitter_DamageModifier: 2

    #
    #  Settings for Unarmed
    ###
    Unarmed:
        # Disarm_ChanceMax: Maximum chance of disarming other players
        # Disarm_MaxBonusLevel: Level when the maximum chance to disarm is reached
        Disarm_ChanceMax: 0.0
        Disarm_MaxBonusLevel: 1000

        # Deflect_ChanceMax: Maximum chance of deflecting arrows
        # Deflect_MaxBonusLevel: Level when the maximum chance to deflect is reached
        Deflect_ChanceMax: 50.0
        Deflect_MaxBonusLevel: 1000

        # IronGrip_ChanceMax: Maximum chance of preventing being disarmed
        # IronGrip_MaxBonusLevel: Level when the maximum chance to prevent being disarmed is reached
        IronGrip_ChanceMax: 100.0
        IronGrip_MaxBonusLevel: 1000

        # IronArm_BonusMax: Maximum bonus damage for unarmed
        # IronArm_IncreaseLevel: Bonus damage increases every increase level
        IronArm_BonusMax: 8
        IronArm_IncreaseLevel: 50
```
