### ISSUE TITLE
Mysql Error - SQL Exception - Admin stats not saved

### ISSUE THREAD

**Issue by Nightreaver** [mcMMO-Dev/mcMMO#1192]
I'm using mcMMO  2097-dev-build.
i switched from SQLite to mysql due to performance and everytime im getting an error.

2013-06-13 14:10:40 [INFO] [mcMMO] Attempting connection to MySQL...
2013-06-13 14:10:41 [INFO] [mcMMO] Connection to MySQL was a success!
2013-06-13 14:10:41 [SEVERE] [mcMMO] SQLException: No operations allowed after connection closed.
2013-06-13 14:10:41 [SEVERE] [mcMMO] SQLState: 08003
2013-06-13 14:10:41 [SEVERE] [mcMMO] VendorError: 0

sadly.. nothing more is written there, but i can see that the stats are not saved correcly, it seems to be problem of me being an "Admin".

i use pex for permission, when i Admin, error occurs and stats are not saved
when I'm a regular user ('Bewohner'), stats are saved, error is gone.

i haven't set any permission.

``` YAML
  Bewohner:
    prefix: '&2Bewohner|&r'
    permissions:
    - modifyworld.*
    - -dynmap.*
    options:
      rank: '900'

  Admin:
    inheritance:
    - Bewohner
    prefix: '&6Admin|&r'
    permissions:
    - permissions.*
    options:
      rank: '1'
```
