### ISSUE TITLE
Biome specifiable Treasure from Excavation/Fishing

### ISSUE THREAD

**Issue by kdthehun** [mcMMO-Dev/mcMMO#1228]
Hi!
I was wondering if it would be possible to add the ability to set Biome Specific Treasures. I like that we can Add our own set of treasures with our own set parameters and modify the existing ones. Like for example I added Emeralds to the treasure list and Quartz and the New Disc "Wait". I was kinda missing them. But i think it would make it more interesting/fun if we could set for example:

```
Emerald:
    ID: 388
    Data: 0
    Amount: 1
    XP: 100
    Drop_Chance: 0.05
    Drop_Level: 650
    Drops_From:
        Grass: true
        Dirt: true
    Biome:
        Extreme_Hills: true
        Taiga: true
        Ocean: false
        Plains: false
        Jungle: true
```

I'm sure you get the idea. This would be interesting to see :)
