### ISSUE TITLE
custom blocks not awarding exp

### ISSUE THREAD

**Issue by psycojoe** [mcMMO-Dev/mcMMO#1267]
Created a blocks file for my server yet none of the ores in the blocks file give any exp, is there a way to fix this or maybe something that I am overlooking?   As far as the mining goes the sulfur and uranium award exp but none of the others

```
# 
#  Settings for Custom Excavation Blocks
###
Excavation:
    Block_1:
        ID: 999
        Data_Value: 0
        XP_Gain: 99
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Block_2:
        ID: 999
        Data_Value: 0
        XP_Gain: 99
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1

#
#  Settings for Custom Herbalism Blocks
###
Herbalism:
    Block_1:
        ID: 999
        Data_Value: 0
        XP_Gain: 99
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Block_2:
        ID: 999
        Data_Value: 0
        XP_Gain: 99
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1

#
#  Settings for Custom Mining Blocks
###
Mining:
    Sulfur_Ore:
        ID: 3880
        Data_Value: 0
        XP_Gain: 600
        Is_Ore: true
        Tier: 1
        Drop_Item: true
        Drop_Item_ID: 4157
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 5
    Uranium_Ore:
        ID: 4095
        Data_Value: 0
        XP_Gain: 400
        Is_Ore: true
        Tier: 1
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Silver_Ore:
        ID: 3989
        Data_Value: 0
        XP_Gain: 550
        Is_Ore: true
        Tier: 1
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Copper_Ore:
        ID: 3970
        Data_Value: 1
        XP_Gain: 250
        Is_Ore: true
        Tier: 1
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Tin_Ore:
        ID: 3971
        Data_Value: 2
        XP_Gain: 250
        Is_Ore: true
        Tier: 1
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Certus_Quartz:
        ID: 902
        Data_Value: 0
        XP_Gain: 500
        Is_Ore: true
        Tier: 1
        Drop_Item: true
        Drop_Item_ID: 4362
        Drop_Item_Data_Value: 6, 7
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 5
    Nether_Quartz:
        ID: 153
        Data_Value: 0
        XP_Gain: 150
        Is_Ore: true
        Tier: 1
        Drop_Item: true
        Drop_Item_ID: 406
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 5
    Osmium_Ore:
        ID: 3002
        Data_Value: 1
        XP_Gain: 350
        Is_Ore: true
        Tier: 1
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1

#
#  Settings for Custom Woodcutting Blocks
###
Woodcutting:
    Rubberwood:
        ID: 212
        Data_Value: 0
        XP_Gain: 99
        Is_Log: true
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Rubber_Wood:
        ID: 627
        Data_Value: 0
        XP_Gain: 99
        Is_Log: true
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Larch_Wood:
        ID: 934
        Data_Value: 0
        XP_Gain: 99
        Is_Log: true
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Teak_Wood:
        ID: 934
        Data_Value: 1
        XP_Gain: 99
        Is_Log: true
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Acacia_Wood:
        ID: 934
        Data_Value: 2
        XP_Gain: 99
        Is_Log: true
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Lime_Wood:
        ID: 934
        Data_Value: 3
        XP_Gain: 99
        Is_Log: true
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Chestnut_Wood:
        ID: 935
        Data_Value: 0
        XP_Gain: 99
        Is_Log: true
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Wenge_Wood:
        ID: 935
        Data_Value: 1
        XP_Gain: 99
        Is_Log: true
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Baobab_Wood:
        ID: 935
        Data_Value: 2
        XP_Gain: 99
        Is_Log: true
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Sequoia_Wood:
        ID: 935
        Data_Value: 3
        XP_Gain: 99
        Is_Log: true
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Kapok_Wood:
        ID: 936
        Data_Value: 0
        XP_Gain: 99
        Is_Log: true
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Ebony_Wood:
        ID: 936
        Data_Value: 1
        XP_Gain: 99
        Is_Log: true
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Mahogany_Wood:
        ID: 936
        Data_Value: 2
        XP_Gain: 99
        Is_Log: true
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Balsa_Wood:
        ID: 936
        Data_Value: 3
        XP_Gain: 99
        Is_Log: true
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Willow_Wood:
        ID: 937
        Data_Value: 0
        XP_Gain: 99
        Is_Log: true
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Walnut_Wood:
        ID: 937
        Data_Value: 1
        XP_Gain: 99
        Is_Log: true
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Greenheart_Wood:
        ID: 937
        Data_Value: 2
        XP_Gain: 99
        Is_Log: true
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Cherry_Wood:
        ID: 937
        Data_Value: 3
        XP_Gain: 99
        Is_Log: true
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Redwood_Log:
        ID: 1312
        Data_Value: 0
        XP_Gain: 99
        Is_Log: true
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Redwood_Log:
        ID: 1313
        Data_Value: 0
        XP_Gain: 99
        Is_Log: true
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Redwood_Log:
        ID: 1314
        Data_Value: 0
        XP_Gain: 99
        Is_Log: true
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Redwood_Log:
        ID: 1315
        Data_Value: 0
        XP_Gain: 99
        Is_Log: true
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Twilight_Oak_Wood:
        ID: 1507
        Data_Value: 0
        XP_Gain: 99
        Is_Log: true
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Canopy_Tree_Wood:
        ID: 1507
        Data_Value: 1
        XP_Gain: 99
        Is_Log: true
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Mangrove_Wood:
        ID: 1507
        Data_Value: 2
        XP_Gain: 99
        Is_Log: true
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Darkwood_Wood:
        ID: 1507
        Data_Value: 3
        XP_Gain: 99
        Is_Log: true
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Timewood:
        ID: 1511
        Data_Value: 0
        XP_Gain: 99
        Is_Log: true
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Transwood:
        ID: 1511
        Data_Value: 1
        XP_Gain: 99
        Is_Log: true
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Minewood:
        ID: 1511
        Data_Value: 2
        XP_Gain: 99
        Is_Log: true
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Sortingwood:
        ID: 1511
        Data_Value: 3
        XP_Gain: 99
        Is_Log: true
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Greatwood_Log:
        ID: 1611
        Data_Value: 0
        XP_Gain: 99
        Is_Log: true
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Silverwood_Log:
        ID: 1611
        Data_Value: 1
        XP_Gain: 99
        Is_Log: true
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1
    Rubber_Wood:
        ID: 3122
        Data_Value: 0
        XP_Gain: 99
        Is_Log: true
        Drop_Item: false
        Drop_Item_ID: 999
        Drop_Item_Data_Value: 0
        Min_Drop_Item_Amount: 1
        Max_Drop_Item_Amount: 1



#
#  Settings for Custom Ability Blocks
#  (These blocks don't trigger abilities)
###
Ability_Blocks:
    Block_1:
        ID: 999
        Data_Value: 0
    Block_2:
        ID: 999
        Data_Value: 0        
```
