### ISSUE TITLE
More Ranks in advanced.yml

### ISSUE THREAD

**Issue by HavenServer** [mcMMO-Dev/mcMMO#1288]
default -         

```
Arcane_Forging:
            May_Lose_Enchants: true
            Rank_Levels:
                Rank_1: 250
                Rank_2: 500
                Rank_3: 1000
                Rank_4: 1500
            Keep_Enchants:
                Chance:
                    Rank_4: 80
                    Rank_3: 40
                    Rank_2: 20
                    Rank_1: 10
            Downgrades:
                Enabled: true
                Chance:
                    Rank_4: 15
                    Rank_3: 25
                    Rank_2: 50
                    Rank_1: 75
```

adding more Rank_5: (info) Rank_6 add so on.. mcmmo seems to delete it on startup? How do I add more ranks to advanced YML?
