### ISSUE TITLE
Errors with repairing and Flux Mining

### ISSUE THREAD

**Issue by Jacold** [mcMMO-Dev/mcMMO#1367]
2013-08-11 01:00:17 [INFO] [mcMMO] Enabling mcMMO v1.4.07-dev1-b2170
2013-08-11 01:00:17 [WARNING] [mcMMO] Skills.Repair.Arcane_Forging.Downgrades.Chance.Rank_4 only accepts values from 1 to 100!
2013-08-11 01:00:17 [WARNING] [mcMMO] Skills.Repair.Arcane_Forging.Keep_Enchants.Chance.Rank_4 only accepts values from 1 to 100!
2013-08-11 01:00:17 [WARNING] [mcMMO] Skills.Smelting.FluxMining_UnlockLevel should be at least 1!
2013-08-11 01:00:17 [WARNING] [mcMMO] Skills.Smelting.FluxMining_Chance should be at least 1!
2013-08-11 01:00:17 [WARNING] [mcMMO] Errors were found in advanced.yml! mcMMO was disabled!
2013-08-11 01:00:17 [INFO] [mcMMO] Disabling mcMMO v1.4.07-dev1-b2170

What are you fail in this? I have configured when player mastered repair skill he have 100% chance to repair enchanted item (and 0% to downgrade/remove enchant). My config in this section:

```
    Arcane_Forging:
        May_Lose_Enchants: true
        Rank_Levels:
            Rank_1: 250
            Rank_2: 500
            Rank_3: 750
            Rank_4: 1000
        Keep_Enchants:
            Chance:
                Rank_4: 100
                Rank_3: 60
                Rank_2: 30
                Rank_1: 10
        Downgrades:
            Enabled: true
            Chance:
                Rank_4: 0
                Rank_3: 10
                Rank_2: 50
                Rank_1: 80
```

Next thing is Flux Mining. I don't want this and I'm set these values to 0.

```
    FluxMining_UnlockLevel: 0
    FluxMining_Chance: 0
```

And I can't run my server.
Please, fix it As Fast As Possible...

Cheers, Jacold.
