### ISSUE TITLE
Repair config errors, build 3227

### ISSUE THREAD

**Issue by yendor5691** [mcMMO-Dev/mcMMO#1484]
<h2>Version Info</h2>

Minecraft 1.6.4
Spigot 1114
Essentials vDev2.12.121
mcMMO 3227 with optional chainmail.repair.yml

<h2>Bug Description</h2>

Upon start-up, I get the following errors: 

```
15:02:56 [WARNING] [mcMMO] Maximum durability of BUCKET must be greater than 0!
15:02:56 [WARNING] [mcMMO] Minimum quantity of CARROT_STICK must be greater than 0!
```

Salvage of a bucket works correctly, no repair needed.  
Carrot on a Stick will not repair and Salvage produces no products, just destroys Carrot on a Stick.  Adding         MinimumQuantity: 2 
to the CARROT_STICK configuration did not change the behavior.  
Salvage of Chainmail Armor does not work, consistent with prior behavior.  

<b>Change chainmail.repair.yml for custom recipe:  </b>

```
Repairables:
    #
    # Chainmail repairables
    ###
    # Armor
    CHAINMAIL_HELMET:
        RepairMaterial: IRON_FENCE
        XpMultiplier: 2
        MinimumQuantity: 5
    CHAINMAIL_CHESTPLATE:
        RepairMaterial: IRON_FENCE
        XpMultiplier: 2
        MinimumQuantity: 8
    CHAINMAIL_LEGGINGS:
        RepairMaterial: IRON_FENCE
        XpMultiplier: 2
        MinimumQuantity: 7
    CHAINMAIL_BOOTS:
        RepairMaterial: IRON_FENCE
        XpMultiplier: 2
        MinimumQuantity: 4
```

<b>Additional Errors</b>

```
15:02:56 [WARNING] [mcMMO] Minimum quantity of CHAINMAIL_HELMET must be greater than 0!
15:02:56 [WARNING] [mcMMO] Minimum quantity of CHAINMAIL_CHESTPLATE must be greater than 0!
15:02:56 [WARNING] [mcMMO] Minimum quantity of CHAINMAIL_LEGGINGS must be greater than 0!
15:02:56 [WARNING] [mcMMO] Minimum quantity of CHAINMAIL_BOOTS must be greater than 0!
```

Chainmail armor could not be repaired or salvaged.
