### ISSUE TITLE
Mod tools return "Invalid material name"

### ISSUE THREAD

**Issue by Arthan-the-one** [mcMMO-Dev/mcMMO#1509]
Entering mod tools into the ModItems/tools.yml results in e.g:

```
    [mcMMO] Invalid material name. This item will be skipped. - Stone_Paxel
```

this seems to be due to some lines in src\main\java\com\gmail\nossr50\config\mods\CustomToolConfig.java; namely:
(line 72)

```
    Set<String> toolConfigSet = toolSection.getKeys(false);

    for (String toolName : toolConfigSet) {
        Material toolMaterial = Material.matchMaterial(toolName);

        if (toolMaterial == null) {
            plugin.getLogger().warning("Invalid material name. This item will be skipped. - " + toolName);
            continue;
        }
```

which leads to the Item name being compared to the bukkit material enum, thus returning null and causing mod items not named after one of the vanilla materials to be ignored.

Instead of a proper Name, using for example Stone instead of Stone_Paxel, it works.

using [MCPC+](http://ci.md-5.net/job/MCPC-Plus/56/), and [Xnets paxel Mod](http://www.minecraftforum.net/topic/1778540-162-xnets-paxel-mod-its-back/)
this is a minimal example not working tools.yml

```
    Axes:
        Stone_Paxel:
            ID: 14505
            XP_Modifer: 1.0
            Ability_Enabled: true
            Tier: 2
            Repairable: true
            Repair_Material_ID: 5
            Repair_Material_Data_Value: 0
            Repair_Material_Quantity: 7
            Durability: 331
```
