### ISSUE TITLE
Tools.yml

### ISSUE THREAD

**Issue by T451kevin** [mcMMO-Dev/mcMMO#1612]
When I put stuff in the tools.yml nothing is added to mcmmo and that is the pickaxe of the core ID from Thaumcraft 4

My question is am I putting the info in correctly?

``` yml
Pickaxe_1: 25329
        XP_Modifer: 1.0
        Ability_Enabled: true
        Tier: 1
        Repairable: true
        Repair_Material: 25356
        Repair_Material_Data_Value: 2
        Repair_Material_Quantity: 3
        Durability: 1500
```
