### ISSUE TITLE
treasures.yml - how to add item with metadata?

### ISSUE THREAD

**Issue by Jacold** [mcMMO-Dev/mcMMO#1624]
```
   SAPLING:
        Amount: 1
        Data: 5
        XP: 1000
        Drop_Chance: 0.1
        Drop_Level: 3
        Drops_From: [Grass]
```

Because of new format of this file I don't know how to put this onto config.  I want to add all saplings to drops from grass. How can I do that?
