### ISSUE TITLE
BUG about the Hardcore setting.

### ISSUE THREAD

**Issue by 233sama** [mcMMO-Dev/mcMMO#1661]
Mcmmo is a wonderful plugin , but still have bugs ~

```
#  Settings for Hardcore mode
###
Hardcore:
    Death_Stat_Loss:
        Penalty_Percentage: 5
        Enabled:
            Acrobatics: true
            Archery: false
            Axes: true
            Fishing: true
            Herbalism: false
            Mining: true    
            Repair: false
            Swords: true
            Taming: false
            Unarmed: false
            Woodcutting: true
```

my config.yml like this , you can see i turn off the Repair Death stat loss ,
but when player die , the Repair still drops the level , can you fix it ?
thanks for your teams work =D
