### ISSUE TITLE
Hardcore not working with CombatTag b3417

### ISSUE THREAD

**Issue by FuRiouSOne** [mcMMO-Dev/mcMMO#1688]
Any reason hardcore isnt working?

Running spigot 1180 and mcMMO b3417 and when player dies by another player hardcore or vampirism is not working.

Also tested when dying to mobs, players do not lose stats.
```
#  Settings for Hardcore mode
###
Hardcore:
    Death_Stat_Loss:
        Penalty_Percentage: 35
        Enabled:
            Acrobatics: true
            Archery: true
            Axes: true
            Fishing: true
            Herbalism: true
            Mining: true
            Repair: true
            Swords: true
            Taming: true
            Unarmed: true
            Woodcutting: true
            Excavation: false
    Vampirism:
        Leech_Percentage: 25
        Enabled:
            Acrobatics: true
            Archery: true
            Axes: true
            Fishing: true
            Herbalism: true
            Mining: true
            Repair: true
            Swords: true
            Taming: true
            Unarmed: true
            Woodcutting: true
            Excavation: false
```
