### ISSUE TITLE
Chunklets..?

### ISSUE THREAD

**Issue by Plutoren** [mcMMO-Dev/mcMMO#1724]
Okay so I've located the hidden.yml file, changed it to chunklets: false, Re uploaded this plugin with that saved and everything. (I was told to do this in my last submission) However I'm still not receiving xp for the blocks I've set to regenerate through the "mineral manager" plugin. (Which is the entire world's ores/trees) Can anyone explain how to allow mcmmo to give xp for these self-regenerating blocks...?

Here is the hidden.yml config I have setup currently, if that helps

```
Options:
    # true to use Chunklets metadata store system, false to disable
    Chunklets: false
    # Square root of the number of chunks to convert per tick.
    ConversionRate: 1
    # true to use enchantment buffs for Super Breaker & Giga Drill Breaker, false to use potion buffs
    EnchantmentBuffs: true
    # true to enable refreshing of chunks around a player at the end of Super Breaker, Giga Drill Breaker, and Berserk.  This should fix blocks being broken client side, but not server-side
    RefreshChunks: false
```

If some things show up bold I have no idea why...
