### ISSUE TITLE
A Iittle Question of potions.yml

### ISSUE THREAD

**Issue by jefffliu** [mcMMO-Dev/mcMMO#1817]
I just only reading src / main / resources / potions.yml to learn about Alchemy skill.
and saw that

```
    4352: # Potion of Hunger
        Effects: ["HUNGER 0 900"]
        Children:
            GLOWSTONE_DUST: 4384
            REDSTONE: 4416
            SULPHUR: 20736
    4284: # Potion of Hunger II
        Effects: ["HUNGER 1 450"]
        Children:
            REDSTONE: 4416
            SULPHUR: 20768
    4416: # Potion of Hunger Extended
        Effects: ["HUNGER 0 2400"]
        Children:
            GLOWSTONE_DUST: 4384
            SULPHUR: 20800
```

Potion of Hunger II maybe is 4384 not 4284.
(I didn't test. i just only reading this file)
