### ISSUE TITLE
Death penalty 1% instead of 10%?

### ISSUE THREAD

**Issue by Jacold** [mcMMO-Dev/mcMMO#1823]
Hello. I have set 10% penalty (a long ago) when player dies but players reported that they lose only 1%. My config:

```
    Death_Stat_Loss:
        Penalty_Percentage: 10.0
        Enabled:
            Acrobatics: true
            Archery: true
            Axes: true
            Excavation: true
            Fishing: true
            Herbalism: true
            Mining: true
            Repair: true
            Swords: true
            Taming: true
            Unarmed: true
            Woodcutting: true
            Alchemy: true
        Level_Threshold: 0
```

Where can I find solution?
