### ISSUE TITLE
data value mistake in potions.yml

### ISSUE THREAD

**Issue by goosewoman** [mcMMO-Dev/mcMMO#1844]
```
8195: # Potion of Fire Resistance
    Effects: ["FIRE_RESISTANCE 0 3600"]
    Children:
        REDSTONE: 3139
```

it says 3139
 it should be 8259
because that's the data value of an extended fire resistance potion
 https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/resources/potions.yml#L298
It produces some wonky results with essentials' /itemdb
