### ISSUE TITLE
Vampirism do not work in  mcMMO 1.5.00

### ISSUE THREAD

**Issue by spindyzzer** [mcMMO-Dev/mcMMO#2024]
Hello. 
Vampirism do not work in  mcMMO 1.5.00 (Bukkit 1.7.9). Any solution?

The config:

```
Hardcore:
    Death_Stat_Loss:
        Penalty_Percentage: 1.0
        Level_Threshold: 0
        Enabled:
            Acrobatics: true
            Alchemy: true
            Archery: true
            Axes: true
            Excavation: true
            Fishing: true
            Herbalism: true
            Mining: true
            Repair: true
            Swords: true
            Taming: true
            Unarmed: true
            Woodcutting: true
    Vampirism:
        Leech_Percentage: 5.0
        Level_Threshold: 0
        Enabled:
            Acrobatics: true
            Alchemy: true
            Archery: true
            Axes: true
            Excavation: true
            Fishing: true
            Herbalism: true
            Mining: true
            Repair: true
            Swords: true
            Taming: true
            Unarmed: true
            Woodcutting: true
```

Thanks
