### ISSUE TITLE
While repairing spent only oak boards. Other boards are in inventory. 

### ISSUE THREAD

**Issue by Disko-partizani** [mcMMO-Dev/mcMMO#2082]
Hello!
What's wrong?
tools.

```
     X26467:
           XP_Modifer: 1
           Ability_Enabled: true
           Tier: 1
           Repairable: true
           Repair_Material: Wood
           Repair_Material_Data_Value: 0
           Repair_Material_Quantity: 4
           Durability: 119
```

 repair.

```
      X26467:
           MaterialType: Wood
           RepairMaterial: Wood
           RepairMaterialMetadata: -1
           MinimumLevel: 0
           XpMultiplier: .18
           MaximumDurability: 119
```
