### ISSUE TITLE
One hit kill

### ISSUE THREAD

**Issue by Adder991** [mcMMO-Dev/mcMMO#2114]
Critical hits one hit people:

```
    CriticalHit:
        ChanceMax: 37.5
        MaxBonusLevel: 750
        # Damage modifier of critical hits for PVP / PVE, when causing a critical hit the damage gets multiplied by the modifier
        PVP_Modifier: 1.5
        PVE_Modifier: 2.0
```
