### ISSUE TITLE
Change partial extract to comply with full extract.

### ISSUE THREAD

**Issue by mcMMO** [mcMMO-Dev/mcMMO#2267]
1. ExtractPartialEnchant 7 has to be lower than 8, 7, 6 and so on.
2. Partial extract should comply with full extract values. Example:
   
   ```
       # ExtractFullEnchant: Chance to extract the full enchant at each ArcaneSalvage rank
       ExtractFullEnchant:
           Rank_1: 70.0
           Rank_2: 60.0
           Rank_3: 50,0
           Rank_4: 40,0
           Rank_5: 30,0
           Rank_6: 20,0
           Rank_7: 10.0
           Rank_8: 0.0
   
       # ExtractPartialEnchant: Chance to extract the partial enchant at each ArcaneSalvage rank
       ExtractPartialEnchant:
           Rank_1: 30.0
           Rank_2: 40.0
           Rank_3: 50.0
           Rank_4: 60.0
           Rank_5: 70.0
           Rank_6: 80.0
           Rank_7: 90.0
           Rank_8: 100.0
   ```
