### ISSUE TITLE
UnlockLevel should be changed to Rank

### ISSUE THREAD

**Issue by mcMMO** [mcMMO-Dev/mcMMO#2268]
For example:

```
        UnlockLevel: 0
        MaxBonusLevel: 100
```

to:

```
        UnlockRank: 1
        MaxBonusLevel: 100
```

and:

```
    # Rank_Levels: Alchemy level where rank gets unlocked
    Rank_Levels:
        Rank_1: 0
        Rank_2: 1
        Rank_3: 2
        Rank_4: 3
        Rank_5: 4
        Rank_6: 5
        Rank_7: 6
        Rank_8: 7
```

so the ability gets unlocked at level 0 in this case.
