### ISSUE TITLE
Rank levels should be allowed to be 0 or same as higher.

### ISSUE THREAD

**Issue by mcMMO** [mcMMO-Dev/mcMMO#2270]
Read title, eg.

```
        Rank_Levels:
            Rank_1: 0
            Rank_2: 0
            Rank_3: 20
            Rank_4: 30
            Rank_5: 40
            Rank_6: 50
            Rank_7: 50
            Rank_8: 50
```
