### ISSUE TITLE
Disarm ability issue and feature request

### ISSUE THREAD

**Issue by Theepwner** [mcMMO-Dev/mcMMO#2430]
It seems as if the ChanceMax for disarm is a bit inaccurate.  I initially tried to disable the ability by setting the ChanceMax to 0, but was alarmed because the lowest it allows you to set it is 1.  Now with ChanceMax at 1, it seems that players disarming each other still happens quite frequently, and it feels more than 1%.

Could you possibly make it so you can disable the "disarm" feature of mcmmo?  Also, is it just me that feels the ChanceMax is weird?  By 1%, does that mean out of all players' hits with unarmed, or the individual players' chance?

Thanks.

**Comment by zRiaz** [comment]
You can completely disable unarmed by giving your players the permisson node for it just with a - before it. -mcmmo.unarmed (not sure if thats the permission) but its around that.. You can look around for the permission yourself.

**Comment by Theepwner** [comment]
Damn, totally forgot about the permission nodes for mcMMO.

Thanks!

**Comment by TfT-02** [comment]
Setting ChanceMax to 1% means that, at the maximum bonus level you will have 1% chance of disarming another player. The levels 0 to the maximum bonus levels will have a chance which is linearly calculated.

Example:
```
    Unarmed:
        Disarm:
            # ChanceMax: Maximum chance of disarming other players
            # MaxBonusLevel: Level when the maximum chance to disarm is reached
            # AntiTheft: Determines if only the disarmed player can retrieve disarmed items
            ChanceMax: 1.0
            MaxBonusLevel: 50
```
Chance to disarm another player at level 50 = 1%, chance to disarm another player at level 25 = 0,5%
