### ISSUE TITLE
Cannot disable Mob_Healthbar

### ISSUE THREAD

**Issue by Xericore** [mcMMO-Dev/mcMMO#2536]
Version: 1.5.03-SNAPSHOT-b46
The following configuration still displays the Mob_Healthbar:
```
Mob_Healthbar:
    # Display_Type: Default display for mob health bars - HEARTS, BAR, or DISABLED
    # Display_Time: Amount of time (in seconds) to display. To display permanently, set to -1
    Display_Type: DISABLED
    Display_Time: -1
```
Setting Display_Time: 0 doesn't work as mcMMO then refuses to start.

**Comment by DahFrozen** [comment]
I'm having the same problem. It's extremely annoying. Hopefully it will get fixed soon.

**Comment by Xericore** [comment]
I worked around this by disabling it in CombatUtils.handleHealthbars(). I don't have time to look into the mcMMO code and to provide a proper fix, but you can add a return statement in that method and build the .jar yourself. That works for me, but please note that this completely disables the healthbar feature.

**Comment by TfT-02** [comment]
That just changes the default setting, to disable use the permission node
https://github.com/mcMMO-Dev/mcMMO/wiki/Frequently-asked-questions#how-do-the-new-mob-healthbars-work

**Comment by Xericore** [comment]
To be honest, I forgot to mention that I have tried negating the permission as well, but that didn't work either.
Here's how my permissions.yml (PEX) looks like:
```
groups:
  default:
    options:
      default: true
    permissions:
    - -mcmmo.mobhealthdisplay
```
