### ISSUE TITLE
Arena Deaths (like Mob Arena) Remove Levels when on Hardcore

### ISSUE THREAD

**Issue by graywolf336** [mcMMO-Dev/mcMMO#309]
I have a couple Mob Arenas on my server because people love them on my server and because we've spent some time on them making custom classes and what not but because we have this in the config:

``` yaml
Hardcore:
  Enabled: true
  Death_Stat_Loss_Penalty_Percentage: 30
  Vampirism: false
  Vampirism_Stat_Leech_Percentage: 5
```

Players no longer like to play in the arenas due to them losing their levels. I was thinking that since Mob Arena has custom events that it throws out that mcMMO could listen for those to hook into it. For example here are some of the events being used: https://github.com/acstache/MobArenaGod/blob/master/src/com/ACStache/ArenaGodPlus/PluginListeners/MobArenaListener.java#L38

One other thing that I'd like to see is maybe with this you could have an option to disable mcMMO abilties in Mob Arena..that would be super!
