### ISSUE TITLE
Mod Mobs McmmoTaming & Experience

### ISSUE THREAD

**Issue by ConflictReigns** [mcMMO-Dev/mcMMO#3170]
Thanks for the amazing plugin.

There aren't any examples of actually implementing the entities config file for mods.  I've included an attempt at a 1.7.10 mutantcreatures mob 'creeperminion.'  Taming it, though a somewhat unique endeavor, does not yield taming experience.  Call of the wild also does not summon it.  I have tried this with a few other mobs.

edit**
Another issue is that attacking vanilla mobs does not yield mcmmo swords experience.  I tried zombies skeletons, creepers, and magma cubes.  I'll extrapolate and guess that it won't work for other combat types as well.  Maybe it is a side effect of having mods entities enabled so I'll try to test that later.  I looked through the configs to make sure it wasn't something else.  Oddly I get exp from mod mobs.
edit**
I disabled mod entities in the configs.  I now get experience from vanilla and mod mobs.  Still, I can't use call of the wild on tameable mod mobs.

Regards, The_Breeze_Knees
```
mutantcreatures_creeperminion:
  Class: Monster
  XP_Multiplier: 1.0
  Tameable: true
  Taming_XP: 3000
  CanBeSummoned: true
  COTW_Material: 289
  COTW_Material_Data: 0
  COTW_Material_Amount: 32
```
