### ISSUE TITLE
Green thumb does not replant.

### ISSUE THREAD

**Issue by mibby** [mcMMO-Dev/mcMMO#3215]
McMMO dev 192
Paper dev 1139 (Spigot 1.12)

McMMO herbalism green thumb skill does not replant crops whatsoever. I set my herbalism level to 1500. When I try breaking a crop (wheat) with seeds in my inventory, it does not replant. Functionality broken?

```
        GreenThumb:
            # StageChange: Level value when the GreenThumb stage rank goes up
            # ChanceMax: Maximum chance of GreenThumb when on <MaxBonusLevel> or higher
            # MaxBonusLevel: On this level, GreenThumb chance will be <ChanceMax>
            StageChange: 200
            ChanceMax: 70.0
            MaxBonusLevel: 1500
```
