### ISSUE TITLE
Vanilla loot with Mcmmo fishing

### ISSUE THREAD

**Issue by Violentmoon** [mcMMO-Dev/mcMMO#3231]
Is there away to enable the vanilla loot table with mcMMO?

**Comment by Zefferis** [comment]
.../mcmmo/config.yml

What you're looking for is the override feature.

Line 325:
```
    Fishing:
        Level_Cap: 0
        Drops_Enabled: true
        Override_Vanilla_Treasures: true
        # Always catch fish, even when treasure is found
        Extra_Fish: true
```
