### ISSUE TITLE
McMMO rejecting repair.custom.yml

### ISSUE THREAD

**Issue by AgentBaron** [mcMMO-Dev/mcMMO#3304]
I am trying to add repairable chainmail armor, shields, and elytra to McMMO but it seems to be rejecting any repair.custom.yml I make. Here are the errors I'm getting:

```
27.09 16:03:21 [Server] INFO [mcMMO] Enabling mcMMO v1.5.09-SNAPSHOT
27.09 16:03:22 [Server] WARN [mcMMO] You are using an old version of the repair.custom.yml file.
27.09 16:03:22 [Server] WARN [mcMMO] Your old file has been renamed to repair.custom.yml.old and has been replaced by an updated version.
27.09 16:03:22 [Server] WARN [mcMMO] Reloading repair.custom.yml with new values...
27.09 16:03:22 [Server] ERROR [mcMMO] There was an error while enabling mcMMO!
27.09 16:03:22 [Server] WARN java.lang.IllegalArgumentException: The embedded resource 'mcMMO/repair.custom.yml' cannot be found in plugins/mcMMO 1.5.09-SNAPSHOT.jar
27.09 16:03:22 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.saveResource(JavaPlugin.java:195)
27.09 16:03:22 [Server] WARN at com.gmail.nossr50.config.ConfigLoader.loadFile(ConfigLoader.java:37)
27.09 16:03:22 [Server] WARN at com.gmail.nossr50.config.ConfigLoader.backup(ConfigLoader.java:87)
27.09 16:03:22 [Server] WARN at com.gmail.nossr50.config.skills.repair.RepairConfig.loadKeys(RepairConfig.java:36)
27.09 16:03:22 [Server] WARN at com.gmail.nossr50.config.skills.repair.RepairConfig.<init>(RepairConfig.java:24)
27.09 16:03:22 [Server] WARN at com.gmail.nossr50.config.skills.repair.RepairConfigManager.<init>(RepairConfigManager.java:34)
27.09 16:03:22 [Server] WARN at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:411)
27.09 16:03:22 [Server] WARN at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:145)
27.09 16:03:22 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
27.09 16:03:22 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
27.09 16:03:22 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
27.09 16:03:22 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:384)
27.09 16:03:22 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:333)
27.09 16:03:22 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206)
27.09 16:03:22 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
27.09 16:03:22 [Server] WARN at java.lang.Thread.run(Unknown Source)
27.09 16:03:22 [Server] INFO [mcMMO] Disabling mcMMO v1.5.09-SNAPSHOT
27.09 16:03:22 [Server] ERROR Error occurred while disabling mcMMO v1.5.09-SNAPSHOT (Is it up to date?)
27.09 16:03:22 [Server] INFO java.lang.NullPointerException: null
27.09 16:03:22 [Server] INFO at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:245) ~[?:?]
27.09 16:03:22 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
27.09 16:03:22 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
27.09 16:03:22 [Multicraft] Skipped 42 lines due to rate limit (30/s)
```

I don't think it's necessary, but here is the code inside my yml file:
```
#
#  Repair configuration
#  Last updated on 1.5.05-b143
#
# Any file named repair.*.yml in the mcmmmo folder will be loaded as a repair config
# All repair configs have a main section titled "Repairables"
# Afterwards, all sub-items are considered a Repairable to be loaded. The names of each subitem should be the exact material name.
# The bare minimum of a Repairable is that it have a RepairMaterial and a MaximumDurability
#
# ItemType: This is the type of item to be repaired, this is only important to permissions.
## Valid values are ARMOR, TOOL, and OTHER.
## This defaults to OTHER.
#
# MaterialType: This is the type of the material of the item to be repaired, this is only important for permissions.
## Valid values are STRING, LEATHER, WOOD, STONE, IRON, GOLD, DIAMOND, and OTHER
## This defaults to OTHER.
#
# RepairMaterial: This is the material name of the item used to repair this repairable.
## This is required to be set.
#
# RepairMaterialMetadata: This is the metadata of the item used to repair this repairable.
## A value of -1 means to ignore all metadata when repairing.
## This defaults to -1
#
# MaximumDurability: This is the maximum durability of the item.
## This is required to be set.
#
# MinimumLevel: This is the minimum repair level needed to repair this item.
## Valid values are => 0
## This defaults to 0
#
# MinimumQuantity: This is the minimum number of items needed to repair this item ignoring all other repair bonuses.
## This is typically the number of the repair material needed to create a new item, for example for a sword it is 2, for an axe it is 3
## This defaults to 2
#
# XpMultiplier: This is the amount to multiply the xp bonus by.
## This defaults to 1
#
#
# The following is the default repair config that ships with mcMMO, it contains all vanilla items that are repairable.
#
#
###
# Custom repairables
Repairables:
     CHAINMAIL_HELMET:
        ItemId: 302
        ItemType: ARMOR
        MaterialType: IRON
        MaximumDurability: 165
        MinimumQuantity: 4
        XpMultiplier: 0.5
    CHAINMAIL_CHESTPLATE:
        ItemId: 303
        ItemType: ARMOR
        MaterialType: IRON
        MaximumDurability: 241
        MinimumQuantity: 6
        XpMultiplier: 0.5
    CHAINMAIL_LEGGINGS:
        ItemId: 304
        ItemType: ARMOR
        MaterialType: IRON
        MaximumDurability: 225
        MinimumQuantity: 5
        XpMultiplier: 0.5
    CHAINMAIL_BOOTS:
        ItemId: 305
        ItemType: ARMOR
        MaterialType: IRON
        MaximumDurability: 195
        MinimumQuantity: 3
        XpMultiplier: 0.5
    # Shield
    SHIELD:
        ItemId: 442
        ItemType: OTHER
        MaterialType: OTHER
        RepairMaterialId: 5
        RepairMaterialMetadata: -1
        MaximumDurability: 337
        MinimumQuantity: 6
        XpMultiplier: 0.5
    # Elytra
    ELYTRA:
        ItemId: 443
        ItemType: OTHER
        MaterialType: LEATHER
        MaximumDurability: 431
        MinimumQuantity: 8
        XpMultiplier: 1.5
```

**Comment by AgentBaron** [comment]
I am still trying to get this working. I've now added RepairMaterial as I realized that was needed, but at the end of the day mcMMO is still rejecting it. If I add the .yml directly to the jar, it freaks into a loop where it loads the original 'repair.custom.yml' from the jar and thinks it's an old version. It keeps going until it gives up and refuses to load mcMMO.

```
Repairables:
    #
    ###
    # Chainmail Armor
    CHAINMAIL_HELMET:
        ItemId: 302
        ItemType: ARMOR
        MaterialType: OTHER
        RepairMaterial: IRON
        RepairMaterialId: 265
        RepairMaterialMetadata: -1
        MaximumDurability: 165
        MinimumQuantity: 4
        XpMultiplier: 0.5
    CHAINMAIL_CHESTPLATE:
        ItemId: 303
        ItemType: ARMOR
        MaterialType: OTHER
        RepairMaterial: IRON
        RepairMaterialId: 265
        RepairMaterialMetadata: -1
        MaximumDurability: 241
        MinimumQuantity: 6
        XpMultiplier: 0.5
    CHAINMAIL_LEGGINGS:
        ItemId: 304
        ItemType: ARMOR
        MaterialType: OTHER
        RepairMaterial: IRON
        RepairMaterialId: 265
        RepairMaterialMetadata: -1
        MaximumDurability: 225
        MinimumQuantity: 5
        XpMultiplier: 0.5
    CHAINMAIL_BOOTS:
        ItemId: 305
        ItemType: ARMOR
        MaterialType: OTHER
        RepairMaterial: IRON
        RepairMaterialId: 265
        RepairMaterialMetadata: -1
        MaximumDurability: 195
        MinimumQuantity: 3
        XpMultiplier: 0.5
    # Shield
    SHIELD:
        ItemId: 442
        ItemType: OTHER
        MaterialType: OTHER
        RepairMaterial: WOOD
        RepairMaterialId: 5
        RepairMaterialMetadata: -1
        MaximumDurability: 337
        MinimumQuantity: 6
        XpMultiplier: 0.5
    # Elytra
    ELYTRA:
        ItemId: 443
        ItemType: OTHER
        MaterialType: LEATHER
        RepairMaterial: LEATHER
        RepairMaterialId: 334
        MaximumDurability: 431
        MinimumQuantity: 8
        XpMultiplier: 1.5
```
