### ISSUE TITLE
Tabcomplete 1.13 permissions issue.

### ISSUE THREAD

**Issue by LogGits** [mcMMO-Dev/mcMMO#3625]
Tabcomplete in 1.13 allows players to view commands that they don't have the permission to use. This is because the plugin.yml file is setup incorrectly to handle permissions. An example of a plugin.yml setup that would stop people from tabcompleting commands that they don't have the perms to use.
```yaml
commands:
  start:
    description: hub of important commands.
    aliases: info
    permission: test.start

permissions:
  test.start:
    description: give access to /start
    default: true
```
