### ISSUE TITLE
Support for MythicMobs items in treasures?

### ISSUE THREAD

**Issue by EHAndrew** [mcMMO-Dev/mcMMO#3640]
There is no documentation that says that this is supported, so here's the feature request. I would like the ability for items created within MythicMobs to be added to treasures.yml. I am including possible formatting below. Note: MythicMobs internal names are case sensitive.
```
Excavation:
    MythicMobs_<MM_Internal_Item_Name>:
        Amount: 1
        XP: 200
        Rarity: COMMON
```
or...
```
Excavation:
    <MM_Internal_Item_Name>:
        Type: MythicMobs
        Amount: 1
        XP: 200
        Rarity: COMMON
```
