### ISSUE TITLE
[Bug] IronArmStyle IncreaseLevel does not scale with RetroMode.

### ISSUE THREAD

**Issue by mibby** [mcMMO-Dev/mcMMO#3723]
McMMO dev 450
https://papermc.io/ci/view/all/job/mcMMO/

@nossr50 Noticed IronArmStyle does not scale with RetroMode enabled. You get +8 damage at level 50 unarmed instead of 500. The other skills seem to scale by *10.

Haven't checked if there are other stats not scaling with RetroMode yet.

```
    #
    #  Settings for Unarmed
    ###
    Unarmed:
        Disarm:
            # ChanceMax: Maximum chance of disarming other players
            # MaxBonusLevel: Level when the maximum chance to disarm is reached
            # AntiTheft: Determines if only the disarmed player can retrieve disarmed items
            ChanceMax: 33.0
            MaxBonusLevel: 100
            AntiTheft: false

        ArrowDeflect:
            # ChanceMax: Maximum chance of deflecting arrows
            # MaxBonusLevel: Level when the maximum chance to deflect is reached
            ChanceMax: 50.0
            MaxBonusLevel: 100

        IronGrip:
            # ChanceMax: Maximum chance of preventing being disarmed
            # MaxBonusLevel: Level when the maximum chance to prevent being disarmed is reached
            ChanceMax: 100.0
            MaxBonusLevel: 100

        IronArmStyle:
            # BonusMin: Minimum bonus damage for unarmed
            # BonusMax: Maximum bonus damage for unarmed
            # IncreaseLevel: Bonus damage increases every increase level
            BonusMin: 3.0
            BonusMax: 8.0
            IncreaseLevel: 5
```
