### ISSUE TITLE
[Bug] ExperienceGain ActionBarNotifications is sending a BossBar display instead of ActionBar display.

### ISSUE THREAD

**Issue by mibby** [mcMMO-Dev/mcMMO#3725]
McMMO dev 450
https://papermc.io/ci/view/all/job/mcMMO/

@nossr50 Noticed that xp gain is displaying a boss bar message at the top instead of an actionbar message above the hotbar. Is this intended? 

Before the modern rewrite, I used the plugin mcMMOAction to display actionbar messages above the hotbar. Figured this is no longer necessary since actionbar support is integrated natively now, but it's displaying a bossbar for xp gain instead. :(

```
Feedback:
    # If sendtitles is true messages will be sent using the title api (BIG TEXT ON SCREEN)
    Events:
        XP:
            SendTitles: true
    #The actionbar is the message location right above the health bar
    ## If you disable the action bar messages, mcMMO will send the message to the chat system instead
    ActionBarNotifications:
        AbilityOff:
            Enabled: true
            SendCopyOfMessageToChat: false
        HardcoreMode:
            Enabled: true
            SendCopyOfMessageToChat: true
        RequirementsNotMet:
            Enabled: true
            SendCopyOfMessageToChat: false
        AbilityCoolDown:
            Enabled: true
            SendCopyOfMessageToChat: false
        LevelUps:
            Enabled: true
            SendCopyOfMessageToChat: true
        Holiday:
            Enabled: true
            SendCopyOfMessageToChat: true
        ToolReady:
            Enabled: true
            SendCopyOfMessageToChat: false
        SubSkillInteraction:
            Enabled: true
            SendCopyOfMessageToChat: false
        SubSkillFailure:
            Enabled: true
            SendCopyOfMessageToChat: false
        SubSkillUnlocked:
            Enabled: true
            SendCopyOfMessageToChat: true
        SuperAbilityInteraction:
            Enabled: true
            SendCopyOfMessageToChat: false
        SuperAbilityAlertOthers:
            Enabled: true
            SendCopyOfMessageToChat: true
        ExperienceGain:
            Enabled: true
            SendCopyOfMessageToChat: false
        ItemMessage:
            Enabled: true
            SendCopyOfMessageToChat: false
        NoPermission:
            Enabled: true
            SendCopyOfMessageToChat: true
        PartyMessage:
            Enabled: true
            SendCopyOfMessageToChat: true
```
