### ISSUE TITLE
Configuration Question: Custom Salvage

### ISSUE THREAD

**Issue by OpalMoonstride** [mcMMO-Dev/mcMMO#3755]
I apologize, but I am receiving an error with the mcMMO-overhauled configuration for salvage; basically it does not understand my salvage material. I am sure I just don't know what the proper syntax is for the config.
I want to add nametag, and saddle, as salvageable. They do not have crafting recipes, because I don't want players to craft them. Can I add them as salvageable without a crafting recipe? How would I do this? 
This is similar to what I have tried:
```
NAME_TAG:
     MinimumLevel: 35
     XpMultiplier: .3
     SalvageMaterial: paper
```

Thank you!!
