### ISSUE TITLE
By default, Mycelium is listed incorrectly under woodcutting in experience.yml

### ISSUE THREAD

**Issue by Quavelen** [mcMMO-Dev/mcMMO#3811]
```yaml
#
#  Settings for XP distribution
###
Experience:
    Woodcutting:
        Mycelium: 70
```

It should not be listed under woodcutting, as it is not harvestable with an axe.
