### ISSUE TITLE
Fisherman's Diet displaying incorrect information.

### ISSUE THREAD

**Issue by CodeByCam** [mcMMO-Dev/mcMMO#3819]
**Server:** PaperMC Build-564.
**mcMMO:** Build 343 using Retro Mode.

As per the title, players are seeing the Fisherman's Diet rank based off (what seems to be) Standard Mode (Rank 5 @ level 100). Although Retro Mode is enabled in the config so they should only be seeing Rank 5 @ level 1000.

![mcMMOBug](https://user-images.githubusercontent.com/41496198/54068268-cb02d980-4296-11e9-9869-9e272b786648.png)

```
    FishermansDiet:
        Standard:
            Rank_1: 20
            Rank_2: 40
            Rank_3: 60
            Rank_4: 80
            Rank_5: 100
        RetroMode:
            Rank_1: 200
            Rank_2: 400
            Rank_3: 600
            Rank_4: 800
            Rank_5: 1000
```
