### ISSUE TITLE
Custom blocks doesn't work?

### ISSUE THREAD

**Issue by ProjectSky** [mcMMO-Dev/mcMMO#3935]
#### I use CatServer Software (1.12.2) https://github.com/CatServer/CatServer

* MCMMO Version: 1.5.10

**Tried with both custom and vanilla tools. No error message in log when the block is broken. servers is able to register the blockbreak. this a known issue?**

* blocks.default.yml
``` yaml
Mining:
    CAVERN_CAVE_BLOCK|0:
        XP_Gain: 160
        Double_Drops_Enabled: true
        Is_Ore: true
        Smelting_XP_Gain: 5
    CAVERN_CAVE_BLOCK|1:
        XP_Gain: 140
        Double_Drops_Enabled: true
        Is_Ore: true
        Smelting_XP_Gain: 5
    CAVERN_CAVE_BLOCK|2:
        XP_Gain: 150
        Double_Drops_Enabled: true
        Is_Ore: true
        Smelting_XP_Gain: 5
```
