### ISSUE TITLE
Experience lineair calculation deviation

### ISSUE THREAD

**Issue by x1p** [mcMMO-Dev/mcMMO#3939]
So the experience formula has changed since 2.1.64. My expectations with this have an deviation I cannot explain (yet). Perhaps some one can shed a light on this.

Settings:
```
EarlyGameBoost:
    Enabled: false
    MaxLevelMultiplier: 0.05

Experience_Formula:
    Linear_Values:
        base: 0
        multiplier: 50
```

Expected curve:
New players joins. He is automatically level 1.
On level 1, he needs 5000 XP till level 2.
On level 2, he needs 10000 XP till level 3.
And so on. You get the idea.

Actual curve:
New players joins. He is automatically level 1.
On level 1, he needs 7750 XP till level 2.
On level 2, he needs 12750 XP till level 3.
On level 3, he needs 17750 XP till level 4.
So there is a bias of 2750.

If the Linear_Values.multiplier is set to 20  the values change.
It needs 3100 XP till level 2 instead of the expected 2000.
That is a bias of 1100.
Conclusion: the first level gets a multiplier of exactly 1.55.
(2000 x 1.55 = 3100 // 5000 x 1.55 = 7750)

The big question is: where does this comes from and can it be turned off/corrected?
