### ISSUE TITLE
[Question] Smelting materials

### ISSUE THREAD

**Issue by x1p** [mcMMO-Dev/mcMMO#3949]
I want to add some materials to the smelting section of experience.yml that don't belong there by default.
What do I need to add additional materials?

For example:
```
Experience_Values:
    Smelting:
        Coal_Ore: 10
        Sand: 5
```
