### ISSUE TITLE
Additional Skill - Alchemy

### ISSUE THREAD

**Issue by EasyMFnE** [mcMMO-Dev/mcMMO#405]
I have a custom local branch of mcMMO with the following skill added:

Alchemy
- Brewing Mastery - Chance of brewing potions successfully.
- Catalysis - Varied brewing time based upon skill level
- Scholar of Time - Ability to brew Extended potions
- Scholar of Power - Ability to brew Tier II potions
- Scholar of Detonation - Ability to brew Splash potions

Fully configurable via AdvancedConfig:

```
Alchemy:
    Brew_ChanceMax: 100
    Brew_ChanceMin: 25
    Brew_Success_MaxBonusLevel: 1000
    Brew_TimeMax: 1200
    Brew_TimeMin: 100
    Brew_Time_MaxBonusLevel: 1000
    Redstone_Unlock: 100
    Glowstone_Unlock: 200
    Gunpowder_Unlock: 300
    Failed_Potions:
    - 55
    - 59
    - 61
    - 63
    Failure_XP: 200
    Success_XP: 600
```

I would like to know if the mcMMO-Dev team would be interested in adding this functionality to the plugin.  I would be glad to share my source code.

Further notes:
Potions always fail if the player does not have the Scholar effect necessary for the resultant potion.  All potions are subjected to the random chance defined through Brewing Mastery.  Failed potions are chosen randomly from the defined list, or if no list is present, the potion remains what it was before the most recent ingredient was added.  (I also have a small helper plugin that adds configurable negative effects to the unused-in-vanilla potions, but it is not necessary).  If a player does not have permission for Alchemy, the vanilla potion brewing behavior is unchanged.

![2012-12-31_15 21 31](https://f.cloud.github.com/assets/3160455/36933/70005cc2-5389-11e2-8a85-562bf34e3346.png)
