### ISSUE TITLE
Fishing override to vanilla treasures not applying on config

### ISSUE THREAD

**Issue by Vealoth** [mcMMO-Dev/mcMMO#4150]
I set the fishing treasure override to false in the config, and restarted many times. No effect. I had to disable the skill. Please fix this.

**Comment by evilryan** [comment]
I am also having this problem. Here is my config section for fishing:

```
    Fishing:
        Level_Cap: 0
        Drops_Enabled: true
        Override_Vanilla_Treasures: false #true
        # Always catch fish, even when treasure is found
        Extra_Fish: false
        Lure_Modifier: 4.0
```
