### ISSUE TITLE
mcmmo.bypass.kraken Doesn't Appear to Work

### ISSUE THREAD

**Issue by HumanJHawkins** [mcMMO-Dev/mcMMO#4216]
Using v.2.1.132 (downloaded 07/04/2020 from official site web link), the mcmmo.bypass.kraken permission does not appear to work. This is installed on a Paper Spigot server 1.16.1 with GriefPrevention, WorldEdit, WorldGuard, and QuickShop.

I say "appear" because I don't have authoritative info on what it is supposed to do. But I'm trying to turn off the prevention of fishing in the same spot. With this permission set to true, either via LuckPerms or via the permissions.yml file in the Paper build, I can only cast about 10 times before I get a message that it appears there are no more fish, and I should move 3 blocks. No Kracken appears, but I read that this was supposed to disable all anti-repetitive fishing code.

mcMMO is great, but this is a negative for my server. I don't have cheaters. But I have some players that love to fish and who find this to impede their fun.

Thanks.

**Comment by Ineusia** [comment]
The Kraken was removed in mcMMO version 2.1.0 

You can find the toggle for the FishingExploitFix in experience.yml

```
ExploitFix:
    COTWBreeding: true
    UnsafeEnchantments: false
    # Prevent many exploits related to fishing
    Fishing: true
```
