### ISSUE TITLE
Smelting Nether Gold Ore Does Not Give Bonus Drops

### ISSUE THREAD

**Issue by delbertina** [mcMMO-Dev/mcMMO#4249]
Possibly a bug with how the bonus drops list works since gold ingot is already in that list and that's what nether gold ore smelts into. Tried deleting the mcmmo folder, restarting the server, and editing in the values in these 2 sections. Also changed bonus drop max chance to 100% for testing, but that probably has nothing to do with the cause of the issue.

Running 2.1.138 w/ Paper 1.16.1 build 130

Config.yml > Bonus_Drops >
```
    Smelting:
        Iron_Ingot: true
        Gold_Ingot: true
        Emerald: true
        Diamond: true
        Lapis_Lazuli: true
        Coal: true
        Nether_Quartz: true
        Quartz: true
        Redstone: true
        Netherite_Scrap: true
```

Experience.yml > Experince_Values >
```
Smelting:
        Ancient_Debris: 200
        Coal_Ore: 10
        Diamond_Ore: 75
        Emerald_Ore: 100
        Gold_Ore: 35
        Iron_Ore: 25
        Lapis_Ore: 40
        Nether_Quartz_Ore: 25
        Nether_Gold_Ore: 25
        Redstone_Ore: 15
```
