### ISSUE TITLE
[Support] How to add Shake?

### ISSUE THREAD

**Issue by mrfloris** [mcMMO-Dev/mcMMO#4280]
Hey there,

I can't get Shake on Drowned and Donkeys etc. to work. 

What should I add to which file specifically to add Shake to the new mobs that we've had for a bit, like

Colored Sheep, Husk, Stray, Donkey, Drowned, and would it be possible to have different shake results if it's not a white sheep?

**Comment by nossr50** [comment]
Can you show examples of the entries you tried already?
It should be enough if you do this

```yaml
Shake:
    NAME_OF_MOB:
        NAME_OF_ITEM:
            Amount: 1
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
```

As for the different results of shake per different colours of sheep, I'll have to add some code to support that so I'll consider it a feature request.

**Comment by mrfloris** [comment]
```
    Drop_Chance: 50.0
            Drop_Level: 0
        GOLD_NUGGET:
            Amount: 1
            XP: 0
            Drop_Chance: 50.0
            Drop_Level: 0
    PLAYER:
        SKELETON_SKULL:
            Amount: 1
            XP: 0
            Drop_Chance: 0.0
            Drop_Level: 0
        INVENTORY:
            Whole_Stacks: false
            Drop_Chance: 0.0
            Drop_Level: 0
    SHEEP:
        WHITE_WOOL:
            Amount: 3
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
        ORANGE_WOOL:
            Amount: 3
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
        PURPLE_WOOL:
            Amount: 3
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
        BLUE_WOOL:
            Amount: 3
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
        BROWN_WOOL:
            Amount: 3
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
        GREEN_WOOL:
            Amount: 3
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
        RED_WOOL:
            Amount: 3
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
        BLACK_WOOL:
            Amount: 3
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
        MAGENTA_WOOL:
            Amount: 3
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
        LIGHT_BLUE_WOOL:
            Amount: 3
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
        YELLOW_WOOL:
            Amount: 3
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
        LIME_WOOL:
            Amount: 3
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
        PINK_WOOL:
            Amount: 3
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
        GRAY_WOOL:
            Amount: 3
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
        LIGHT_GRAY_WOOL:
            Amount: 3
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
        CYAN_WOOL:
            Amount: 3
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
```
treasures.yml

Yeah, would be nice to get colored sheep support after all these years, I hope it's possible. It only drops wool, and when the sheep has it (not when it lost it), and colored sheep drop white too. 

Going to try and add the missing mobs on my list (and per mob ill consider if it's worth adding or why/whynot)

Currently not under shake in treasures are
```
BAT
BEE
CAT
DOLPHIN
DONKEY
DROWNED
ELDER_GUARDIAN
ENDER_DRAGON
ENDERMITE
EVOKER
FOX
GIANT
GUARDIAN
HOGLIN
HUSK
ILLUSIONER
LLAMA
MULE
OCELOT
PANDA
PARROT
PHANTOM
PIGLIN
PIGLIN_BRUTE
PILLAGER
POLAR_BEAR
RABBIT
RAVAGER
SALMON
SILVERFISH
SKELETON_HORSE
STRAY
STRIDER
TRADER_LLAMA
TRIDENT
TURTLE
VEX
VILLAGER
VINDICATOR
WANDERING_TRADER
WITHER
WOLF
ZOGLIN
ZOMBIE_HORSE
ZOMBIE_VILLAGER
```
i haven't touched treasures in months since i upgraded and let it generate, which is probably at the end of 1.15.2, so possible some of these made it to the default now. ill compare in my own time later.

**Comment by mrfloris** [comment]
seems pig_zombie is still the default for 1.16.3 
https://github.com/mcMMO-Dev/mcMMO/blob/fdd951f1f1890d4bcb62fb6d44fd576df63ad8fe/src/main/resources/treasures.yml

the treasures.yml is the same as the 1.15 one, the list above are all the api entitytype that aren't on it (though a bunch wont make sense)

might be worth to consider adding a few as new defaults, a lot has changed since 1.12.

**Comment by nossr50** [comment]
Thanks for the list that is helpful. I don't know if I mentioned this yet, but every loot table in Treasures will be updated in the config update (and allow for much better customization). The loot tables system is also going to be reworked into something similar to what is used in Bethesda games.

**Comment by mrfloris** [comment]
Double check the list, i might have left a fish on there or something that should not be. 
The ones i've added today to my own server were these, and hearing back from the other staff as to what they think i should add.

```
#
#  Settings for Shake
#  If you are in retro mode, Drop_Level is multiplied by 10.
###
Shake:
    BLAZE:
        BLAZE_ROD:
            Amount: 1
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
    CAVE_SPIDER:
        SPIDER_EYE:
            Amount: 1
            XP: 0
            Drop_Chance: 49.0
            Drop_Level: 0
        STRING:
            Amount: 1
            XP: 0
            Drop_Chance: 49.0
            Drop_Level: 0
        COBWEB:
            Amount: 1
            XP: 0
            Drop_Chance: 1.0
            Drop_Level: 0
        POTION|0|POISON:
            PotionData:
                PotionType: POISON
            Amount: 1
            XP: 0
            Drop_Chance: 1.0
            Drop_Level: 0
    CHICKEN:
        FEATHER:
            Amount: 1
            XP: 0
            Drop_Chance: 33.3
            Drop_Level: 0
        CHICKEN:
            Amount: 1
            XP: 0
            Drop_Chance: 33.3
            Drop_Level: 0
        EGG:
            Amount: 1
            XP: 0
            Drop_Chance: 33.3
            Drop_Level: 0
    COW:
        MILK_BUCKET:
            Amount: 1
            XP: 0
            Drop_Chance: 2.0
            Drop_Level: 0
        LEATHER:
            Amount: 1
            XP: 0
            Drop_Chance: 49.0
            Drop_Level: 0
        BEEF:
            Amount: 1
            XP: 0
            Drop_Chance: 49.0
            Drop_Level: 0
    CREEPER:
        CREEPER_HEAD:
            Amount: 1
            XP: 0
            Drop_Chance: 1.0
            Drop_Level: 0
        GUNPOWDER:
            Amount: 1
            XP: 0
            Drop_Chance: 99.0
            Drop_Level: 0
    ENDERMAN:
        ENDER_PEARL:
            Amount: 1
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
    GHAST:
        GUNPOWDER:
            Amount: 1
            XP: 0
            Drop_Chance: 50.0
            Drop_Level: 0
        GHAST_TEAR:
            Amount: 1
            XP: 0
            Drop_Chance: 50.0
            Drop_Level: 0
    HORSE:
        LEATHER:
            Amount: 1
            XP: 0
            Drop_Chance: 99.0
            Drop_Level: 0
        SADDLE:
            Amount: 1
            XP: 0
            Drop_Chance: 1.0
            Drop_Level: 0
    SKELETON_HORSE:
        LEATHER:
            Amount: 1
            XP: 0
            Drop_Chance: 99.0
            Drop_Level: 0
        SADDLE:
            Amount: 1
            XP: 0
            Drop_Chance: 1.0
            Drop_Level: 0
        BONE:
            Amount: 1
            XP: 0
            Drop_Chance: 1.0
            Drop_Level: 0
    MULE:
        LEATHER:
            Amount: 1
            XP: 0
            Drop_Chance: 50.0
            Drop_Level: 0
        GOLDEN_HORSE_ARMOR:
            Amount: 1
            XP: 0
            Drop_Chance: 1.0
            Drop_Level: 0
        BONE:
            Amount: 1
            XP: 0
            Drop_Chance: 1.0
            Drop_Level: 0
    LLAMA:
        LEATHER:
            Amount: 1
            XP: 0
            Drop_Chance: 50.0
            Drop_Level: 0
        LIGHT_BLUE_CARPET:
            Amount: 1
            XP: 0
            Drop_Chance: 1.0
            Drop_Level: 0
        LEAD:
            Amount: 1
            XP: 0
            Drop_Chance: 1.0
            Drop_Level: 0
    ZOMBIE_HORSE:
        LEATHER:
            Amount: 1
            XP: 0
            Drop_Chance: 99.0
            Drop_Level: 0
        SADDLE:
            Amount: 1
            XP: 0
            Drop_Chance: 1.0
            Drop_Level: 0
        ROTTEN_FLESH:
            Amount: 1
            XP: 0
            Drop_Chance: 2.0
            Drop_Level: 0
    DONKEY:
        LEATHER:
            Amount: 1
            XP: 0
            Drop_Chance: 50.0
            Drop_Level: 0
        SADDLE:
            Amount: 1
            XP: 0
            Drop_Chance: 1.0
            Drop_Level: 0
        CHEST:
            Amount: 1
            XP: 0
            Drop_Chance: 1.0
            Drop_Level: 0
    IRON_GOLEM:
        PUMPKIN:
            Amount: 1
            XP: 0
            Drop_Chance: 3.0
            Drop_Level: 0
        IRON_INGOT:
            Amount: 1
            XP: 0
            Drop_Chance: 12.0
            Drop_Level: 0
        POPPY:
            Amount: 1
            XP: 0
            Drop_Chance: 85.0
            Drop_Level: 0
    MAGMA_CUBE:
        MAGMA_CREAM:
            Amount: 1
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
    MUSHROOM_COW:
        MILK_BUCKET:
            Amount: 1
            XP: 0
            Drop_Chance: 5.0
            Drop_Level: 0
        MUSHROOM_STEW:
            Amount: 1
            XP: 0
            Drop_Chance: 5.0
            Drop_Level: 0
        LEATHER:
            Amount: 1
            XP: 0
            Drop_Chance: 30.0
            Drop_Level: 0
        BEEF:
            Amount: 1
            XP: 0
            Drop_Chance: 30.0
            Drop_Level: 0
        RED_MUSHROOM:
            Amount: 2
            XP: 0
            Drop_Chance: 30.0
            Drop_Level: 0
    TURTLE:
        COD:
            Amount: 1
            XP: 0
            Drop_Chance: 50.0
            Drop_Level: 0
        TUBE_CORAL_FAN:
            Amount: 1
            XP: 0
            Drop_Chance: 5.0
            Drop_Level: 0
        BRAIN_CORAL_FAN:
            Amount: 1
            XP: 0
            Drop_Chance: 30.0
            Drop_Level: 0
        SCUTE:
            Amount: 1
            XP: 0
            Drop_Chance: 1.0
            Drop_Level: 0
    RABBIT:
        RABBIT:
            Amount: 1
            XP: 0
            Drop_Chance: 5.0
            Drop_Level: 0
        RABBIT_HIDE:
            Amount: 1
            XP: 0
            Drop_Chance: 5.0
            Drop_Level: 0
        RABBIT_STEW:
            Amount: 1
            XP: 0
            Drop_Chance: 1.0
            Drop_Level: 0
        RABBIT_FOOT:
            Amount: 1
            XP: 0
            Drop_Chance: 1.0
            Drop_Level: 0
    PANDA:
        BAMBOO:
            Amount: 1
            XP: 0
            Drop_Chance: 50.0
            Drop_Level: 0
        JUNGLE_SAPLING:
            Amount: 1
            XP: 0
            Drop_Chance: 20.0
            Drop_Level: 0
        TALL_GRASS:
            Amount: 1
            XP: 0
            Drop_Chance: 25.0
            Drop_Level: 0
        WHITE_WOOL:
            Amount: 1
            XP: 0
            Drop_Chance: 25.0
            Drop_Level: 0
    POLAR_BEAR:
        COD:
            Amount: 1
            XP: 0
            Drop_Chance: 5.0
            Drop_Level: 0
        BIRCH_SAPLING:
            Amount: 1
            XP: 0
            Drop_Chance: 5.0
            Drop_Level: 0
        LARGE_FERN:
            Amount: 1
            XP: 0
            Drop_Chance: 1.0
            Drop_Level: 0
        WHITE_WOOL:
            Amount: 1
            XP: 0
            Drop_Chance: 1.0
            Drop_Level: 0
    PIG:
        PORKCHOP:
            Amount: 1
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
    BAT:
        FEATHER:
            Amount: 1
            XP: 0
            Drop_Chance: 60.0
            Drop_Level: 0
        GUNPOWDER:
            Amount: 1
            XP: 0
            Drop_Chance: 40.0
            Drop_Level: 0
    ZOMBIFIED_PIGLIN:
        ROTTEN_FLESH:
            Amount: 1
            XP: 0
            Drop_Chance: 50.0
            Drop_Level: 0
        GOLD_NUGGET:
            Amount: 1
            XP: 0
            Drop_Chance: 50.0
            Drop_Level: 0
    PLAYER:
        SKELETON_SKULL:
            Amount: 1
            XP: 0
            Drop_Chance: 0.0
            Drop_Level: 0
        INVENTORY:
            Whole_Stacks: false
            Drop_Chance: 0.0
            Drop_Level: 0
    SHEEP:
        WHITE_WOOL:
            Amount: 3
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
        ORANGE_WOOL:
            Amount: 3
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
        PURPLE_WOOL:
            Amount: 3
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
        BLUE_WOOL:
            Amount: 3
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
        BROWN_WOOL:
            Amount: 3
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
        GREEN_WOOL:
            Amount: 3
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
        RED_WOOL:
            Amount: 3
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
        BLACK_WOOL:
            Amount: 3
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
        MAGENTA_WOOL:
            Amount: 3
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
        LIGHT_BLUE_WOOL:
            Amount: 3
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
        YELLOW_WOOL:
            Amount: 3
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
        LIME_WOOL:
            Amount: 3
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
        PINK_WOOL:
            Amount: 3
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
        GRAY_WOOL:
            Amount: 3
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
        LIGHT_GRAY_WOOL:
            Amount: 3
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
        CYAN_WOOL:
            Amount: 3
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
    SHULKER:
        SHULKER_SHELL:
            Amount: 1
            XP: 0
            Drop_Chance: 25.0
            Drop_Level: 0
        PURPUR_BLOCK:
            Amount: 1
            XP: 0
            Drop_Chance: 75.0
            Drop_Level: 0
    SKELETON:
        SKELETON_SKULL:
            Amount: 1
            XP: 0
            Drop_Chance: 2.0
            Drop_Level: 0
        BONE:
            Amount: 1
            XP: 0
            Drop_Chance: 49.0
            Drop_Level: 0
        ARROW:
            Amount: 2
            XP: 0
            Drop_Chance: 49.0
            Drop_Level: 0
    STRAY:
        SKELETON_SKULL:
            Amount: 1
            XP: 0
            Drop_Chance: 2.0
            Drop_Level: 0
        BONE:
            Amount: 1
            XP: 0
            Drop_Chance: 49.0
            Drop_Level: 0
        ARROW:
            Amount: 2
            XP: 0
            Drop_Chance: 49.0
            Drop_Level: 0
        BOW:
            Amount: 1
            XP: 0
            Drop_Chance: 1.0
            Drop_Level: 0
    SLIME:
        SLIME_BALL:
            Amount: 1
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
    SPIDER:
        SPIDER_EYE:
            Amount: 1
            XP: 0
            Drop_Chance: 50.0
            Drop_Level: 0
        STRING:
            Amount: 1
            XP: 0
            Drop_Chance: 50.0
            Drop_Level: 0
    SNOWMAN:
        PUMPKIN:
            Amount: 1
            XP: 0
            Drop_Chance: 3.0
            Drop_Level: 0
        SNOWBALL:
            Amount: 2
            XP: 0
            Drop_Chance: 97.0
            Drop_Level: 0
    SQUID:
        INK_SAC:
            Amount: 1
            XP: 0
            Drop_Chance: 100.0
            Drop_Level: 0
    WITCH:
        SPLASH_POTION|0|INSTANT_HEAL:
            PotionData:
                PotionType: INSTANT_HEAL
            Amount: 1
            XP: 0
            Drop_Chance: 1.0
            Drop_Level: 0
        SPLASH_POTION|0|FIRE_RESISTANCE:
            PotionData:
                PotionType: FIRE_RESISTANCE
            Amount: 1
            XP: 0
            Drop_Chance: 1.0
            Drop_Level: 0
        SPLASH_POTION|0|SPEED:
            PotionData:
                PotionType: SPEED
            Amount: 1
            XP: 0
            Drop_Chance: 1.0
            Drop_Level: 0
        GLASS_BOTTLE:
            Amount: 1
            XP: 0
            Drop_Chance: 7.0
            Drop_Level: 0
        GLOWSTONE_DUST:
            Amount: 1
            XP: 0
            Drop_Chance: 15.0
            Drop_Level: 0
        GUNPOWDER:
            Amount: 1
            XP: 0
            Drop_Chance: 15.0
            Drop_Level: 0
        REDSTONE:
            Amount: 1
            XP: 0
            Drop_Chance: 15.0
            Drop_Level: 0
        SPIDER_EYE:
            Amount: 1
            XP: 0
            Drop_Chance: 15.0
            Drop_Level: 0
        STICK:
            Amount: 1
            XP: 0
            Drop_Chance: 15.0
            Drop_Level: 0
        SUGAR:
            Amount: 1
            XP: 0
            Drop_Chance: 15.0
            Drop_Level: 0
    WITHER_SKELETON:
        WITHER_SKELETON_SKULL:
            Amount: 1
            XP: 0
            Drop_Chance: 2.0
            Drop_Level: 0
        BONE:
            Amount: 1
            XP: 0
            Drop_Chance: 49.0
            Drop_Level: 0
        COAL:
            Amount: 2
            XP: 0
            Drop_Chance: 49.0
            Drop_Level: 0
    ZOMBIE:
        ZOMBIE_HEAD:
            Amount: 1
            XP: 0
            Drop_Chance: 2.0
            Drop_Level: 0
        ROTTEN_FLESH:
            Amount: 1
            XP: 0
            Drop_Chance: 98.0
            Drop_Level: 0
    HUSK:
        ZOMBIE_HEAD:
            Amount: 1
            XP: 0
            Drop_Chance: 2.0
            Drop_Level: 0
        ROTTEN_FLESH:
            Amount: 1
            XP: 0
            Drop_Chance: 98.0
            Drop_Level: 0
    DROWNED:
        ZOMBIE_HEAD:
            Amount: 1
            XP: 0
            Drop_Chance: 2.0
            Drop_Level: 0
        ROTTEN_FLESH:
            Amount: 1
            XP: 0
            Drop_Chance: 98.0
            Drop_Level: 0

```
