### ISSUE TITLE
Database cooldown has no string.

### ISSUE THREAD

**Issue by andrewkm** [mcMMO-Dev/mcMMO#4361]
2.1.164
When using /mctop with below config, during cooldown you get the following in console:
[mcMMO] Could not find locale string: Commands.Database.Cooldown
And the following in game:
https://i.imgur.com/MtsvgcO.png
```
#
#  Settings for commands
###
Commands:
    Skills:
        # Turn this off to prevent mcMMO URL links from being sent
        URL_Links: true
    Generic:
        # If true, when using partial names in commands mcMMO will try to look for a match from
        # the offline players. Enabling this might slow the server down if there are a lot of offline players.
        Match_OfflinePlayers: false
    Database:
        # Database command cooldown in milliseconds, cannot be changed below the default value. (1750)
        # Prevents players from spamming /mctop or /mcrank
        Player_Cooldown: 60000
    mcmmo:
        Donate_Message: false
    inspect:
        Max_Distance: 30.0
    ptp:
        Cooldown: 10
        Warmup: 5
        RecentlyHurt_Cooldown: 30
        Accept_Required: true
        Request_Timeout: 60
        # If true, require players to have a mcmmo.commands.ptp.world.[WorldName] permission
        # to teleport to, from, or within any given world.
        World_Based_Permissions: true
```
