### ISSUE TITLE
[Suggestion] Option to run commands at level up.

### ISSUE THREAD

**Issue by Quavelen** [mcMMO-Dev/mcMMO#4386]
Could a configuration option to execute a command at a specified level up be added?
For example:

```yaml
General:
    # When players reach certain level milestones command will be run
    Level_Up_Commands:
        # Whether or not level up commands are enabled
        Enabled: true
        # How often to run commands, you can change this to 1 to always run a command at a level up event, a setting of 100 will limit it to every 100 levels (for example level 100, level 200, etc)
        Milestone_Interval: 100
        Command_Targets:
            # Send a record of the command to the console
            Send_To_Console: true
            # Whether or not to run the command as the player who levelled up
            Run_As_Player: false
            # Whether or not to run the command as console
            Run_As_Console: true
            # Commands to be run
            Commands:
                - example command syntax
                - another example
                - and another

```

Also, could this please be applied to the *power* level as well as normal skill levels?
