### ISSUE TITLE
[BUG] Wrong Catalysis Potion speed 

### ISSUE THREAD

**Issue by emanondev** [mcMMO-Dev/mcMMO#4419]
on advanced.yml
```
Skills:
    General:
        LimitBreak:
            AllowPVE: false
        StartingLevel: 0
        Ability:
            Length:
                Standard:
                    CapLevel: 200
                    IncreaseLevel: 10
                RetroMode:
                    CapLevel: 1000
                    IncreaseLevel: 50
            EnchantBuff: 4
```
&
```    #
    #  Settings for Alchemy
    ###
    Alchemy:
        Catalysis:
            MaxBonusLevel:
                Standard: 200
                RetroMode: 200
            MinSpeed: 1.0
            MaxSpeed: 3.0
```

on skillranks.yml
```
Alchemy:
    Catalysis:
        Standard:
            Rank_1: 0
        RetroMode:
            Rank_1: 0
```

on config.yml
```
General:
        # Turning this on will scale mcMMO around 1-1000 with default scaling factor
        # Everything in your config related to skill level requirements, skill level bonuses, etc will be multiplied by 10 when this mode is on
        # This change is purely cosmetic, it retains the old feel of mcMMO where you could level up thousands of times
    RetroMode:
        # Whether or not level up broadcasts are enabled
        Enabled: false
```

At level 200 my speed is 1.40x
At level 300 my speed is 1.60x
At level 1000 my speed is 3.00x
At level 1200 my speed is 3.00x

Catalysis completely ignores MaxBonusLevel capping itself at 1000
