### ISSUE TITLE
Green Thumb Replanting Bug

### ISSUE THREAD

**Issue by Gilthunderx** [mcMMO-Dev/mcMMO#4534]
Hello Dev,

theres an issue with the Herbalism Green Thumb Auto Replant feature, I disabled all the crops that will make them auto replant. But the NETHER_WART is still auto replanting, it is the only one not working properly.
```

# Disable or Enable the Green Thumb auto replant feature for specific crops, use the name of the block not the crop itemstack
Green_Thumb_Replanting_Crops:
    Carrots: false
    Wheat: false
    Nether_Wart: false
    Potatoes: false
    Beetroots: false
    Cocoa: false
```

**My server is running Purpur version git-Purpur-1126
McMmo version 2.1.196**
