### ISSUE TITLE
mcMMO Action Bar messages not disabling

### ISSUE THREAD

**Issue by TailedPoog420** [mcMMO-Dev/mcMMO#4556]
I tried disabling all action bar messages in the advanced.yml but it seems that the one when an ability has cooled down keeps displaying. Am I doing something wrong or did I miss something obvious?

This is what I have set up in my advanced.yml regarding the action bar stuff:
```
    ActionBarNotifications:
        AbilityOff:
            Enabled: false
            SendCopyOfMessageToChat: true
        HardcoreMode:
            Enabled: false
            SendCopyOfMessageToChat: true
        RequirementsNotMet:
            Enabled: false
            SendCopyOfMessageToChat: true
        AbilityCoolDown:
            Enabled: false
            SendCopyOfMessageToChat: true
        LevelUps:
            Enabled: false
            SendCopyOfMessageToChat: true
        Holiday:
            Enabled: false
            SendCopyOfMessageToChat: true
        ToolReady:
            Enabled: false
            SendCopyOfMessageToChat: true
        SubSkillInteraction:
            Enabled: false
            SendCopyOfMessageToChat: true
        SubSkillFailed:
            Enabled: false
            SendCopyOfMessageToChat: true
        SubSkillUnlocked:
            Enabled: false
            SendCopyOfMessageToChat: true
        SuperAbilityInteraction:
            Enabled: false
            SendCopyOfMessageToChat: true
        SuperAbilityAlertOthers:
            Enabled: false
            SendCopyOfMessageToChat: true
        ExperienceGain:
            Enabled: false
            SendCopyOfMessageToChat: true
        ItemMessage:
            Enabled: false
            SendCopyOfMessageToChat: true
        NoPermission:
            Enabled: false
            SendCopyOfMessageToChat: true
        PartyMessage:
            Enabled: false
            SendCopyOfMessageToChat: true
```

**Comment by TheBusyBiscuit** [comment]
Can't see anything that's wrong at a quick glance, do you have a screenshot of the message that appears?

**Comment by TailedPoog420** [comment]
![2021-06-23_22 26 40](https://user-images.githubusercontent.com/86117769/123096181-2b22e700-d472-11eb-80ba-6c2ac81d735b.png)
@TheBusyBiscuit

**Comment by TheBusyBiscuit** [comment]
Yep, can confirm that this is missing.
Seems like it was forgotten in the default `advanced.yml`, you can add it yourself though and it should work:

```yaml
        AbilityRefreshed:
            Enabled: false
            SendCopyOfMessageToChat: true
```
