### ISSUE TITLE
Do not respect  SilkTouch setting BlastMining

### ISSUE THREAD

**Issue by broken1arrow** [mcMMO-Dev/mcMMO#4682]
It drops or blocks when it should be diamonds or raw ores.

But seams not work at all on diamonds.

**Comment by broken1arrow** [comment]
Same issue in 1.17.1 404 and version 2.1.20

Do not care about my setting in BlastMining.

```
  Mining:
        SuperBreaker:
            AllowTripleDrops: true
        DoubleDrops:
            SilkTouch: false
            # ChanceMax: Maximum chance of receiving double drops when on <MaxBonusLevel> or higher
            # MaxBonusLevel: Level when <ChanceMax> of receiving double drops is reached
            ChanceMax: 100.0
            MaxBonusLevel:
                Standard: 100
                RetroMode: 1000

        BlastMining:
            # BlastDamageDecrease Ranks: % of damage reduced from TNT explosions
            BlastDamageDecrease:
                Rank_1: 0.0
                Rank_2: 0.0
                Rank_3: 0.0
                Rank_4: 25.0
                Rank_5: 25.0
                Rank_6: 50.0
                Rank_7: 50.0
                Rank_8: 100.0

            # OreBonus Ranks: % of extra ores received when Blast Mining
            OreBonus:
                Rank_1: 35.0
                Rank_2: 40.0
                Rank_3: 45.0
                Rank_4: 50.0
                Rank_5: 55.0
                Rank_6: 60.0
                Rank_7: 65.0
                Rank_8: 70.0
```

![2021-12-29_14 30 28](https://user-images.githubusercontent.com/16368286/147667443-c37837f1-1daf-4c6d-b7af-bf617db79e30.png)
7
