### ISSUE TITLE
Party level update spam

### ISSUE THREAD

**Issue by TheBentoBox** [mcMMO-Dev/mcMMO#4686]
My party was at my max configured level of 10 and I suddenly out of the blue started getting tons of party level increase spam (sound included) every time anyone in my party gained mcMMO XP:

![image](https://user-images.githubusercontent.com/6902229/145941572-c6714f1d-9fb5-48ce-a3a8-76502623e715.png)

Party data:
```yml
Pridelands:
  Leader: 6d000b39-6ebd-42c2-a95a-b3923d87d392|Mr_Simba
  Password: thot
  Locked: true
  Level: 10
  Xp: 0
  Ally: ''
  ExpShareMode: NONE
  ItemShareMode: NONE
  ItemShareType:
    LOOT: true
    MINING: true
    HERBALISM: true
    WOODCUTTING: true
    MISC: true
  Members:
  - 6d000b39-6ebd-42c2-a95a-b3923d87d392|Mr_Simba
  - d46a5a95-9d40-4e9b-9227-9ec88fae1301|MrJoned
  - a4d1abfe-6469-4472-acc3-481e5fab8b78|beccc
  - ec560643-8b15-43c6-ae6b-29f2f0fa4317|Lumberjik1
  - cef9ba78-8d52-4d7a-9aa1-ebd1354b9828|Schwump
  - 9ec51b0f-b8cd-44f0-b0ab-2a6caf28a5f1|CubicBits
  - 3c78fa74-6d20-4552-a580-36f30dc0e9ac|Frostearrific
  - de76681e-283b-4631-97f3-523a7cde6f2c|recyroni
  - 9345b6a5-0af5-4dd5-9720-37eb45c5aadf|LunaPotato
  - f1f28377-a4b3-475c-8f43-218566c51d3e|ossome
```
