### ISSUE TITLE
Taming not gives XP

### ISSUE THREAD

**Issue by mare-on** [mcMMO-Dev/mcMMO#4704]
Hi, I'm using McMMO 2.1.207 with Paper 1.18.1_build132 and I have some issues with taming.
By default in experience.yml is this:

```
    Taming:
        Animal_Taming:
            Axolotl: 600
            Bee: 100
            Cat: 500
            Donkey: 1000
            Fox: 1000
            Goat: 250
            Horse: 1000
            Llama: 1200
            Mule: 1000
            Ocelot: 500
            Panda: 1000
            Parrot: 1100
            Skeleton_Horse: 1000
            Wolf: 250
            Zombie_Horse: 1000
```

But only few of these mobs can be tamed and get some McMMO XP.
For example Axelotl, Bee, Panda doesn't work... is it just McMMO bug or it's just not possible to get XP from taming / breeding some animals?
