### ISSUE TITLE
wont enable / extremely slow enable times. (since changing to aikar jvm options)

### ISSUE THREAD

**Issue by spidertyler2005** [mcMMO-Dev/mcMMO#4715]
I changed my JVM arguments to follow the recommended from the `/timings report` website. these are the "aikar" options.

Ever since I have done this, mcmmo either wont load or will takes 10+ minutes to load. I was wondering why this would happen? 

server info:
```yaml
server-software: purpur (latest)
game-version: 1.18.1
Mcmmo-version: compiled from master (1/8/2022).
xms: 4G
xmx: 4G
```

exact jvm args:
```bash
java -Xms4G -Xmx4G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:InitiatingHeapOccupancyPercent=15 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar paper.jar nogui
```
