### ISSUE TITLE
Alchemy experience bug

### ISSUE THREAD

**Issue by austv** [mcMMO-Dev/mcMMO#4785]
I'm using that configuration to experience the alchemy:

```
    Modifier:
        Alchemy: 2.0

    Alchemy:
        Potion_Stage_1: 24
        Potion_Stage_2: 52
        Potion_Stage_3: 120
        Potion_Stage_4: 260
        Potion_Stage_5: 440
```
A player of my server recorded a bug.
Glowstone dust granted 180EXP for that stage of this custom potion (haste).
And redstone granted 660EXP for that same stage of the same custom potion.

https://www.youtube.com/watch?v=6dfVdzpnxYk&ab_channel=S3v4n
