### ISSUE TITLE
1162 Repair custom RF settings being ignored

### ISSUE THREAD

**Issue by FuRiouSOne** [mcMMO-Dev/mcMMO#490]
Updated to 1162 build and custom RF settings are being ignored and using default settings regardless what i do. I have regenerated a new fresh advance and config yml and still no change.

```
    Arcane_Forging:
        May_Lose_Enchants: true
        Rank_Levels:
            Rank_1: 100
            Rank_2: 500
            Rank_3: 1000
            Rank_4: 2000
    Keep_Enchants:
        Chance:
            Rank_4: 80
            Rank_3: 50
            Rank_2: 25
            Rank_1: 10
    Downgrades:
         Enabled: true
         Chance:
             Rank_4: 10
             Rank_3: 25
             Rank_2: 50
             Rank_1: 75
```
