### ISSUE TITLE
Add lists of supported tools

### ISSUE THREAD

**Issue by vgrynch** [mcMMO-Dev/mcMMO#4926]
Issue:
Currently, in McMMO I do not see a way to define different exp dependent on the tool use, or different chances of treasures dependent on the tool. Would be good, for example, if the golden pick axe gives more exp and treasures.
Also, currently, custom tools (from mods or data packs) do not work at all! (I know it can be done, the "Tree Feller" plugin allows adding custom Axes in config to use, so probably could be done here as well for pick axes, custom weapons etc.)

Proposal:
Add a list of tools for every skill and exp multiplier + treasure chance multiplier. The list may be formatted the same way as items in experience.yml, for example:
```
Tools:
    Fishing:
        Fishing_Rod:
            exp: 1.0
            tr: 1.0
        Fancy_Fishing_Rod:
            exp: 1.1
            tr: 1.5
    Herbalism:
        Hand:
            exp: 1.0
            tr: 1.0
        Wooden_Hoe:
            exp: 1.05
            tr: 1.0
        ........
    Mining:
        ....
        Gold_Pick_Axe:
            exp: 2.0
            tr: 5.0
        ....
```
