### ISSUE TITLE
Limit Tree Feller

### ISSUE THREAD

**Issue by remykczech** [mcMMO-Dev/mcMMO#4965]
Hello,

Is there a way of limiting how many block does Tree Feller affect? Now it is possible to farm whole farm of planted seeds next to each other..

Thanks a lot!

**Comment by SrBedrock** [comment]
I believe it's in config.yml:

```yaml
Abilities:
    Limits:
        Tree_Feller_Threshold: 1000
```
