### ISSUE TITLE
Formula ??? ? ? ? ? ?

### ISSUE THREAD

**Issue by kahlilnc** [mcMMO-Dev/mcMMO#508]
```
Formula:
    Curve_Modifier: 20 # <<<<< WHAT IS THIS <<<<<
    Multiplier:
        Swords: 0.2 # This is lower right?
        Taming: 0.9
        Acrobatics: 0.3
        Excavation: 1.0
        Herbalism: 1.0
        Unarmed: 0.2
        Woodcutting: 1.0
        Mining: 0.7
        Archery: 0.7
        Axes: 0.4
        Repair: 1.0
        Fishing: 1.0
```

I need help with this. I am trying to lower the amount of exp gained per skill but for some reason ppl are leveling up unarmed and swords in 1 mob killllll!!!! Well those are just the ones being reported to me.
