### ISSUE TITLE
Feature Request: Auto-cleanup old backups

### ISSUE THREAD

**Issue by BigScary** [mcMMO-Dev/mcMMO#5084]
I noticed today my mcmmo backup folder is 360mb! Yes I can clean it up on occasion, but it would be just wonderful if old backups were auto-cleaned. I can't imagine anyone would want to roll back more than a couple of weeks..? It could be a config option defaulting to 15 days or so.

Thanks for the amazing plugin! My players love it.

**Comment by IAISI** [comment]
On latest mcmmo? There's this in config.yml:

```
#
#  Settings for Backups
#  Allow mcMMO to create zip backups for config files and flatfile data on shutdown.
# ##
Backups:
    Enabled: true
    
    Keep:
        Last_24_Hours: true
        Daily_Last_Week: true
        Weekly_Past_Months: true
```

Which actually works on all of our servers.
