### ISSUE TITLE
mace cripple sound can't be turned off?

### ISSUE THREAD

**Issue by mrfloris** [mcMMO-Dev/mcMMO#5091]
When we have cripple in `/mace` - when we hit mobs we hear the anvil sound a lot. We want to turn this off

sounds.yml from mcmmo/ folder has
```yaml
    CRIPPLE:
        Enable: false
        Volume: 1.0
        Pitch: 0.5
```
i set it from true to false, and restarted the server, but the anvil sound is still there 

is it another setting? or a bug? or do i misunderstand the issue?
