### ISSUE TITLE
How to add TRIDENT to salvage.vanilla.yml?

### ISSUE THREAD

**Issue by mrfloris** [mcMMO-Dev/mcMMO#5110]
Sorry for the dumb question, it's not there by default, but we can repair it
```yaml
    TRIDENT:
        MinimumLevel: 0
        XpMultiplier: 3
        ItemType: TOOL
        ItemMaterialCategory: OTHER
        RepairMaterial: PRISMARINE_CRYSTALS
        MinimumQuantity: 16
        MaximumDurability: 250
```
It's a bit unclear to me how to properly set the material it will drop and if I can just add it at the bottom of the yml file.
