### ISSUE TITLE
Brewing Bug – All Potions Brew To Extended --> +FIX.

### ISSUE THREAD

**Issue by RussDev7** [mcMMO-Dev/mcMMO#5172]
Within the latest release (1.21.5) of this plugin, I'm experiencing an issue with brewing. When brewing any potion, *ex: poison or strength*, attempting to make the **base** Stage 1 variant will skip to the **extended** redstone version (Stage 2) of the potion. Skill levels have no play in this glitch, you can be lvl1 or lvl100.

**Steps to Reproduce the Bug:**

1. Brew an Awkward potion.
2. Put an spider eye in as an ingredient.
3. Observe your extended potion of poison. (base poison: `00:45`, extended poison: `01:30`)

**What I Have Tested:**

1. Checked for conflicts with other plugins. Created a **fresh** testing environment (using purpur) with only MCMMO as the plugin.
2. Messed around with the `potions.yml` config to find anything to disable this behavior. Nothing fixed it.
3. Confronted ChatGBT to make sure I don't look like an idiot for overlooking something.

![Image](https://github.com/user-attachments/assets/ca1f8a1e-0b9c-4de5-bff1-e99387276c82)

**How I Fixed This Issue:**

```yml
    POTION_OF_POISON:
        Material: POTION
        PotionData:
            PotionType: POISON
            Extended: false # <-- Adding this solved the issue.
        Children:
            GLOWSTONE_DUST: POTION_OF_POISON_II
            FERMENTED_SPIDER_EYE: POTION_OF_HARMING
            GUNPOWDER: SPLASH_POTION_OF_POISON
            REDSTONE: POTION_OF_POISON_EXTENDED
```

Not sure if this fix would be the final implementation as I am sure simply setting the `Extended` Boolean to false by default can easily solve this.
