### ISSUE TITLE
Adjustable skill chances in the config

### ISSUE THREAD

**Issue by Melstrome** [mcMMO-Dev/mcMMO#613]
Add to the config various weapon and ability options to allow better customisation of the skills.

Example:

```
Swords:
    Enabled_For_PVP: true
    Enabled_For_PVE: true
    Damage-Modifier-Per-Level: 0.1
    Bleed-Chance-Per-Level: 0.1
    Level_Cap: 0

Mining:
    Level_Cap: 0
    Requires_Pickaxe: true
    Detonator_ID: 259
    Double-Drop-Chance-Per-Level: 0.1
```
