### ISSUE TITLE
Custom Repair Deleted and Not Working

### ISSUE THREAD

**Issue by Chaznuts** [mcMMO-Dev/mcMMO#764]
My custom additions to the repair and treasures config files have been deleted... again. I believe they might have actually been cleared in one of the 1.4.00 beta versions (usually don't use beta, but had to due to another bug in the previous RB), but haven't confirmed it being cleared in  the current 1.4.00 RB. I have backups, but I am always changing things so backups are not always as easy as copy>paste. 

I tried to re-add my custom repairs, with the first server restart deleting them again and the second server restart leaving them in the .yml, but mcMMO not recognizing them so they were still unrepairable (no errors printed). I have yet to readd my custom treasures as that's a larger task, so I can't tell you yet if the same issue goes to treasures.

mcMMO 1.4.00
CB 1.4.7 R1.1

As I mentioned before, these custom repair additions use to work, but now do not. Here is the additions anyways if you wish to see.

repair.vanilla.yml custom additions:

```
# Chainmail Armor
ChainmailHelmet:
    ItemId: 302
    ItemType: ARMOR
    MaterialType: OTHER
    RepairMaterialId: 263
    RepairMaterialMetadata: -1
    MaximumDurability: 165
    MinimumLevel: 0
    MinimumQuantity: 1
    XpMultiplier: 0.125
ChainmailChest:
    ItemId: 303
    ItemType: ARMOR
    MaterialType: OTHER
    RepairMaterialId: 263
    RepairMaterialMetadata: -1
    MaximumDurability: 241
    MinimumLevel: 0
    MinimumQuantity: 1
    XpMultiplier: 0.125
ChainmailLegs:
    ItemId: 304
    ItemType: ARMOR
    MaterialType: OTHER
    RepairMaterialId: 263
    RepairMaterialMetadata: -1
    MaximumDurability: 225
    MinimumLevel: 0
    MinimumQuantity: 1
    XpMultiplier: 0.125
ChainmailBoots:
    ItemId: 305
    ItemType: ARMOR
    MaterialType: OTHER
    RepairMaterialId: 263
    RepairMaterialMetadata: -1
    MaximumDurability: 195
    MinimumLevel: 0
    MinimumQuantity: 1
    XpMultiplier: 0.125
```
